// Centralized mock data for demo mode — no backend required

export const MOCK_INBOUND_LEADS = [
  { id: 'lead-001', created_at: '2026-05-25T03:14:00Z', source: 'website_form', first_name: 'James', last_name: 'Lim', company: 'Meridian Logistics Pte Ltd', department: 'Finance', email: 'james.lim@meridianlog.com.sg', phone: '+65 9123 4567', topic: 'Trade Credit Insurance', message: 'We are looking for trade credit coverage for our export clients across Southeast Asia. Annual revenue ~SGD 12M.', status: 'qualified', page_url: '/insurance/trade-credit' },
  { id: 'lead-002', created_at: '2026-05-25T05:42:00Z', source: 'email', first_name: 'Sarah', last_name: 'Tan', company: 'Vertex Tech Solutions', department: 'Operations', email: 'sarah.tan@vertextech.sg', phone: '+65 8234 5678', topic: 'Cyber Liability', message: 'Our company processes payments for 50+ enterprise clients. We need cyber liability cover and a business interruption policy.', status: 'proposal', page_url: null },
  { id: 'lead-003', created_at: '2026-05-24T08:10:00Z', source: 'whatsapp_click', first_name: 'Dr. Wei', last_name: 'Chen', company: 'SingHealth Group', department: 'Administration', email: 'wei.chen@singhealth.com.sg', phone: '+65 9345 6789', topic: 'Professional Indemnity', message: 'Looking for PI cover for our team of 45 clinicians. Previous policy is lapsing end of next month.', status: 'engaged', page_url: null },
  { id: 'lead-004', created_at: '2026-05-24T10:30:00Z', source: 'website_form', first_name: 'Raymond', last_name: 'Ho', company: 'Pacific Construction & Engineering', department: 'Procurement', email: 'raymond.ho@pacificce.com.sg', phone: '+65 8456 7890', topic: 'Contractor All Risk', message: 'We have two major projects starting in Q3. Need CAR insurance with 3rd party liability extension.', status: 'new', page_url: '/insurance/construction' },
  { id: 'lead-005', created_at: '2026-05-23T11:15:00Z', source: 'email', first_name: 'Michelle', last_name: 'Wong', company: 'Pinnacle Financial Services', department: 'Compliance', email: 'michelle.wong@pinnfin.com.sg', phone: '+65 9567 8901', topic: 'Directors & Officers Liability', message: 'We are a licensed fund manager. Need D&O and crime insurance for our board and senior officers.', status: 'converted', page_url: null },
  { id: 'lead-006', created_at: '2026-05-23T13:20:00Z', source: 'manual', first_name: 'David', last_name: 'Ong', company: 'AsiaTrade Holdings', department: 'Treasury', email: 'd.ong@asiatrade.com.sg', phone: '+65 8678 9012', topic: 'Marine Cargo', message: 'We import electronics from China and Korea monthly. Looking for open cover marine cargo policy.', status: 'contacted', page_url: null },
  { id: 'lead-007', created_at: '2026-05-22T07:45:00Z', source: 'website_form', first_name: 'Priya', last_name: 'Nair', company: 'Global Pharma Distribution', department: 'Logistics', email: 'priya.nair@globalpharma.sg', phone: '+65 9789 0123', topic: 'Product Liability', message: 'We distribute pharmaceutical products across SEA. Our existing product liability limit seems low given our new contracts.', status: 'engaged', page_url: '/insurance/liability' },
  { id: 'lead-008', created_at: '2026-05-22T09:00:00Z', source: 'claims_form', first_name: 'Kenneth', last_name: 'Lee', company: 'Redstone Property Group', department: 'Asset Management', email: 'kenneth.lee@redstone.com.sg', phone: '+65 8890 1234', topic: 'Property All Risk', message: 'Claim notification: water damage at 22 Tanjong Pagar Plaza affecting 3 floors. Estimated loss SGD 280K.', status: 'contacted', page_url: null },
  { id: 'lead-009', created_at: '2026-05-21T06:30:00Z', source: 'website_form', first_name: 'Amanda', last_name: 'Koh', company: 'Swift Freight International', department: 'Finance', email: 'amanda.koh@swiftfreight.sg', phone: '+65 9901 2345', topic: 'Marine Liability', message: 'We operate 4 vessels in the region. Renewing marine liability — current insurer exit Singapore market.', status: 'qualified', page_url: '/insurance/marine' },
  { id: 'lead-010', created_at: '2026-05-21T08:15:00Z', source: 'email', first_name: 'Thomas', last_name: 'Goh', company: 'Goh Brothers Food Industries', department: 'HR', email: 'thomas.goh@gohbrothers.com.sg', phone: '+65 8012 3456', topic: 'Employee Benefits', message: 'We have 320 staff in 5 outlets. Looking to add dental and optical to our existing group hospitalisation plan.', status: 'new', page_url: null },
  { id: 'lead-011', created_at: '2026-05-20T10:00:00Z', source: 'whatsapp_click', first_name: 'Alicia', last_name: 'Seah', company: 'TechStart SG', department: 'CEO Office', email: 'alicia@techstart.sg', phone: '+65 9123 0001', topic: 'General Business Insurance', message: 'Early stage startup, 18 staff. Need a comprehensive package — public liability, work injury comp, office contents.', status: 'new', page_url: null },
  { id: 'lead-012', created_at: '2026-05-20T12:30:00Z', source: 'website_form', first_name: 'Henry', last_name: 'Tan', company: 'Coastal Marine Services', department: 'Operations', email: 'henry.tan@coastalmarine.sg', phone: '+65 8234 0002', topic: 'Hull & Machinery', message: 'We have a fleet of 6 offshore support vessels. Looking to move hull & machinery coverage to a local broker.', status: 'proposal', page_url: '/insurance/marine' },
  { id: 'lead-013', created_at: '2026-05-19T14:00:00Z', source: 'email', first_name: 'Lisa', last_name: 'Chan', company: 'Chan & Partners Legal LLC', department: 'Managing Partner', email: 'lisa.chan@chanpartners.com.sg', phone: '+65 9345 0003', topic: 'Professional Indemnity', message: 'Our firm handles M&A and property transactions. Looking to increase PI limit from SGD 5M to SGD 15M.', status: 'dropped', page_url: null },
  { id: 'lead-014', created_at: '2026-05-19T16:45:00Z', source: 'website_form', first_name: 'Marcus', last_name: 'Yeo', company: 'Yeo Foodstuff Trading', department: 'Director', email: 'marcus.yeo@yeofoodstuff.sg', phone: '+65 8456 0004', topic: 'Trade Credit Insurance', message: 'Supply sugar and cooking oil to supermarket chains. Worried about buyer credit risk, especially 2 large accounts.', status: 'contacted', page_url: '/insurance/trade-credit' },
  { id: 'lead-015', created_at: '2026-05-18T09:00:00Z', source: 'manual', first_name: 'Rachel', last_name: 'Lau', company: 'CapitalSense Asset Management', department: 'COO', email: 'rachel.lau@capitalsense.sg', phone: '+65 9567 0005', topic: 'Fund Manager Liability', message: 'Referral from MAS compliance consultant. Need FML and PI combo policy for our fund operations.', status: 'qualified', page_url: null },
  { id: 'lead-016', created_at: '2026-05-18T11:30:00Z', source: 'website_form', first_name: 'Ethan', last_name: 'Ng', company: 'Ng Precision Engineering', department: 'CFO', email: 'ethan.ng@ngprecision.sg', phone: '+65 8678 0006', topic: 'Work Injury Compensation', message: 'We employ 85 workers. Our insurer has increased our WIC premium 40% this year — looking for alternatives.', status: 'engaged', page_url: '/insurance/work-injury' },
  { id: 'lead-017', created_at: '2026-05-17T13:15:00Z', source: 'email', first_name: 'Vivian', last_name: 'Lim', company: 'Lim Brothers Shipping', department: 'Finance Director', email: 'vivian.lim@limshipping.sg', phone: '+65 9789 0007', topic: 'Marine Cargo + Hull', message: 'Looking to consolidate our marine portfolio under one broker. Currently have 3 different insurers.', status: 'converted', page_url: null },
  { id: 'lead-018', created_at: '2026-05-17T15:00:00Z', source: 'claims_form', first_name: 'Derek', last_name: 'Sim', company: 'Sim Construction Pte Ltd', department: 'Project Manager', email: 'derek.sim@simconstruction.sg', phone: '+65 8890 0008', topic: 'Claims — Property Damage', message: 'Scaffolding collapse at Jurong site on 16 May. No injuries but significant damage to adjacent property. Urgently need adjuster.', status: 'contacted', page_url: null },
  { id: 'lead-019', created_at: '2026-05-16T08:00:00Z', source: 'website_form', first_name: 'Clara', last_name: 'Tan', company: 'EduPlus International', department: 'Director', email: 'clara.tan@eduplus.sg', phone: '+65 9901 0009', topic: 'Liability Insurance', message: 'We run 4 tuition centres with 600 students. Need public liability and accident coverage for students.', status: 'new', page_url: '/insurance/liability' },
  { id: 'lead-020', created_at: '2026-05-15T10:45:00Z', source: 'email', first_name: 'Ivan', last_name: 'Phua', company: 'Phua & Associates Architects', department: 'Senior Partner', email: 'ivan.phua@phuaarch.sg', phone: '+65 8012 0010', topic: 'Professional Indemnity', message: 'Our firm is expanding to Malaysia and Indonesia. Need PI policy that covers cross-border projects.', status: 'new', page_url: null },
]

export const MOCK_CONTACT_COUNTS = {
  engaged: 8,
  qualified: 5,
  proposal: 3,
  converted: 4,
}

export const MOCK_CONVERSATIONS = [
  { id: 'thread-001', thread_id: 'thread-001', created_at: '2026-05-27T09:30:00Z', source: 'email', subject: 'Re: Trade Credit Insurance Quote – Meridian Logistics', snippet: 'Hi James, thank you for the additional information. I have prepared a comparison of two insurer options...', first_name: 'James', last_name: 'Lim', email: 'james.lim@meridianlog.com.sg', phone: null, company: 'Meridian Logistics', department: 'Finance', contact_type: null, topic: 'Trade Credit Insurance', details: null, message: null, page_url: null, status: 'contacted' },
  { id: 'thread-002', thread_id: 'thread-002', created_at: '2026-05-27T07:15:00Z', source: 'email', subject: 'Cyber Liability Policy – Vertex Tech Solutions', snippet: "Sarah, following up on the cyber liability proposal we sent on Monday. Let me know if you'd like to schedule a call to walk through the terms...", first_name: 'Sarah', last_name: 'Tan', email: 'sarah.tan@vertextech.sg', phone: null, company: 'Vertex Tech Solutions', department: 'Operations', contact_type: null, topic: 'Cyber Liability', details: null, message: null, page_url: null, status: 'contacted' },
  { id: 'thread-003', thread_id: 'thread-003', created_at: '2026-05-26T14:20:00Z', source: 'email', subject: 'Professional Indemnity Renewal – SingHealth', snippet: 'Dr. Chen, I have confirmed with QBE that they can offer the 45-clinician PI policy at a competitive rate. The formal quote is attached...', first_name: 'Wei', last_name: 'Chen', email: 'wei.chen@singhealth.com.sg', phone: null, company: 'SingHealth Group', department: 'Administration', contact_type: null, topic: 'Professional Indemnity', details: null, message: null, page_url: null, status: 'contacted' },
  { id: 'thread-004', thread_id: 'thread-004', created_at: '2026-05-26T10:00:00Z', source: 'email', subject: 'Marine Cargo – Open Cover Proposal', snippet: "Amanda, the open cover proposal from Tokio Marine is ready. Annual premium estimate is SGD 28,400 with a 72-hour discovery clause...", first_name: 'Amanda', last_name: 'Koh', email: 'amanda.koh@swiftfreight.sg', phone: null, company: 'Swift Freight International', department: 'Finance', contact_type: null, topic: 'Marine Cargo', details: null, message: null, page_url: null, status: 'contacted' },
  { id: 'thread-005', thread_id: 'thread-005', created_at: '2026-05-25T16:45:00Z', source: 'email', subject: 'D&O & Crime Insurance – Pinnacle Financial Services', snippet: "Michelle, congratulations — your D&O and crime policy has been bound effective 1 June. Certificate of insurance is attached for your records...", first_name: 'Michelle', last_name: 'Wong', email: 'michelle.wong@pinnfin.com.sg', phone: null, company: 'Pinnacle Financial Services', department: 'Compliance', contact_type: null, topic: 'D&O Liability', details: null, message: null, page_url: null, status: 'contacted' },
  { id: 'thread-006', thread_id: 'thread-006', created_at: '2026-05-25T11:30:00Z', source: 'email', subject: 'Work Injury Compensation – Ng Precision Engineering', snippet: "Ethan, I've obtained quotes from 4 insurers for your WIC policy. The most competitive is AIG at 20% below your current premium...", first_name: 'Ethan', last_name: 'Ng', email: 'ethan.ng@ngprecision.sg', phone: null, company: 'Ng Precision Engineering', department: 'CFO', contact_type: null, topic: 'Work Injury Compensation', details: null, message: null, page_url: null, status: 'contacted' },
  { id: 'thread-007', thread_id: 'thread-007', created_at: '2026-05-24T13:00:00Z', source: 'email', subject: 'Hull & Machinery Insurance – Coastal Marine Services', snippet: "Henry, we have shortlisted 2 Lloyd's syndicates and Tokio Marine for your H&M cover. Can we arrange a brief call this week to review?", first_name: 'Henry', last_name: 'Tan', email: 'henry.tan@coastalmarine.sg', phone: null, company: 'Coastal Marine Services', department: 'Operations', contact_type: null, topic: 'Hull & Machinery', details: null, message: null, page_url: null, status: 'contacted' },
  { id: 'thread-008', thread_id: 'thread-008', created_at: '2026-05-24T09:20:00Z', source: 'email', subject: 'Marine Portfolio Consolidation – Lim Brothers Shipping', snippet: "Vivian, the consolidated marine portfolio is now fully bound. Total annual premium is SGD 142,000, a saving of 18% vs. your previous arrangements...", first_name: 'Vivian', last_name: 'Lim', email: 'vivian.lim@limshipping.sg', phone: null, company: 'Lim Brothers Shipping', department: 'Finance Director', contact_type: null, topic: 'Marine Cargo + Hull', details: null, message: null, page_url: null, status: 'contacted' },
]

export const MOCK_THREAD_DETAILS: Record<string, { thread: Record<string, unknown>; messages: Record<string, unknown>[] }> = {
  'thread-001': {
    thread: { id: 'thread-001', subject: 'Re: Trade Credit Insurance Quote – Meridian Logistics', contact_id: 'c-001', last_message_at: '2026-05-27T09:30:00Z', status: 'active', message_count: 4 },
    messages: [
      { id: 'msg-001a', direction: 'inbound', from_address: 'james.lim@meridianlog.com.sg', subject: 'Trade Credit Insurance Enquiry', body_text: "Hi,\n\nI came across Trade Risk Solutions online and I'm interested in getting trade credit insurance for our logistics company.\n\nWe have about SGD 12M in annual revenue and export to Malaysia, Indonesia and Vietnam. Our main concern is buyer insolvency risk.\n\nCould you send us a quote?\n\nBest regards,\nJames Lim\nFinance Manager, Meridian Logistics", sent_at: '2026-05-25T03:14:00Z', to: ['hello@trade-risksol.com'], cc: [] },
      { id: 'msg-001b', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Re: Trade Credit Insurance Enquiry', body_text: "Hi James,\n\nThank you for reaching out to Trade Risk Solutions. We'd be happy to help Meridian Logistics with trade credit insurance.\n\nTo prepare a tailored quote, could you share:\n1. A list of your top 10 buyers and their approximate credit limits\n2. Any existing credit insurance arrangements\n3. Your preferred policy commencement date\n\nLooking forward to hearing from you.\n\nBest regards,\nSophia Ng\nTrade Risk Solutions", sent_at: '2026-05-25T05:00:00Z', to: ['james.lim@meridianlog.com.sg'], cc: [] },
      { id: 'msg-001c', direction: 'inbound', from_address: 'james.lim@meridianlog.com.sg', subject: 'Re: Trade Credit Insurance Enquiry', body_text: "Hi Sophia,\n\nThanks for the quick response. Here are the details:\n\nTop buyers:\n- PT Nusantara Logistics (Indonesia) — SGD 3.2M exposure\n- MyFreight Sdn Bhd (Malaysia) — SGD 2.8M\n- VN Transport Co. (Vietnam) — SGD 1.5M\n- 7 other buyers totalling ~SGD 4.5M\n\nNo existing credit insurance. We've had one bad debt in the past 3 years (SGD 180K, written off).\n\nHoping to start by 1 July.\n\nJames", sent_at: '2026-05-26T01:30:00Z', to: ['operations@trade-risksol.com'], cc: ['finance@meridianlog.com.sg'] },
      { id: 'msg-001d', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Re: Trade Credit Insurance Quote – Meridian Logistics', body_text: "Hi James,\n\nThank you for the additional information. I have prepared a comparison of two insurer options for your review:\n\nOption 1 — Euler Hermes:\n- Policy limit: SGD 14M aggregate\n- Premium: SGD 42,000 p.a. (0.35% of insured turnover)\n- Coverage: 90% of approved credit limits\n- Waiting period: 6 months for protracted default\n\nOption 2 — Coface:\n- Policy limit: SGD 12M aggregate\n- Premium: SGD 36,800 p.a. (0.31% of insured turnover)\n- Coverage: 85% of approved credit limits\n- Waiting period: 5 months for protracted default\n\nI'd recommend Option 1 given your Indonesian exposure — Euler has stronger claims handling in that market.\n\nShall we schedule a call to discuss?\n\nBest regards,\nSophia Ng", sent_at: '2026-05-27T09:30:00Z', to: ['james.lim@meridianlog.com.sg'], cc: [] },
    ],
  },
  'thread-002': {
    thread: { id: 'thread-002', subject: 'Cyber Liability Policy – Vertex Tech Solutions', contact_id: 'c-002', last_message_at: '2026-05-27T07:15:00Z', status: 'active', message_count: 3 },
    messages: [
      { id: 'msg-002a', direction: 'inbound', from_address: 'sarah.tan@vertextech.sg', subject: 'Cyber Liability Insurance Enquiry', body_text: "Hello,\n\nVertex Tech Solutions provides payment processing services to 50+ enterprise clients. We recently had a security audit that flagged gaps in our cyber risk coverage.\n\nWe need:\n1. Cyber liability (3rd party claims from data breach)\n2. Business interruption if our systems go down\n3. Ideally bundled with our existing professional indemnity\n\nCurrent PI limit is SGD 5M. Can TRS help us review the full package?\n\nSarah Tan\nOperations Director", sent_at: '2026-05-25T05:42:00Z', to: ['hello@trade-risksol.com'], cc: [] },
      { id: 'msg-002b', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Re: Cyber Liability Insurance Enquiry', body_text: "Hi Sarah,\n\nThank you for your message. Cyber liability for payment processors is a specialised area and we work closely with underwriters who understand your sector.\n\nWe can absolutely package cyber, BI and PI together — this typically results in better pricing than purchasing separately.\n\nI'll prepare a proposal covering:\n- Cyber liability up to SGD 10M\n- BI with 30-day indemnity period\n- PI renewal (existing SGD 5M limit review)\n\nTarget to send by Thursday. Could you confirm your year-end date and current PI renewal date?\n\nBest regards,\nMichael Wong\nTrade Risk Solutions", sent_at: '2026-05-25T09:00:00Z', to: ['sarah.tan@vertextech.sg'], cc: [] },
      { id: 'msg-002c', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Cyber Liability Policy – Vertex Tech Solutions', body_text: "Hi Sarah,\n\nFollowing up on the cyber liability proposal we sent on Monday. The AIG Cyber Edge policy I mentioned is available at SGD 68,000 for a SGD 10M limit — which we believe is very competitive given your payment processing activities.\n\nPlease let me know if you'd like to schedule a call to walk through the terms. I'm available Thursday 2–5pm or Friday morning.\n\nBest regards,\nMichael Wong", sent_at: '2026-05-27T07:15:00Z', to: ['sarah.tan@vertextech.sg'], cc: ['it@vertextech.sg'] },
    ],
  },
  'thread-003': {
    thread: { id: 'thread-003', subject: 'Professional Indemnity Renewal – SingHealth', contact_id: 'c-003', last_message_at: '2026-05-26T14:20:00Z', status: 'active', message_count: 3 },
    messages: [
      { id: 'msg-003a', direction: 'inbound', from_address: 'wei.chen@singhealth.com.sg', subject: 'Urgent: PI Insurance Renewal', body_text: "Hi,\n\nI am reaching out regarding our professional indemnity insurance which expires on 30 June.\n\nWe have 45 clinicians (30 doctors, 15 allied health professionals). Our previous insurer has declined to renew due to a claim last year (SGD 320K settlement — cardiac procedure complication).\n\nWe need a new PI policy urgently. Are you able to assist?\n\nDr. Wei Chen\nAdministration, SingHealth Group", sent_at: '2026-05-24T08:10:00Z', to: ['hello@trade-risksol.com'], cc: [] },
      { id: 'msg-003b', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Re: Urgent: PI Insurance Renewal', body_text: "Dear Dr. Chen,\n\nThank you for reaching out. We understand the urgency and can help.\n\nClinician PI with a prior claim is a specialist placement — we work with Lloyd's syndicates who are comfortable with medical indemnity in Singapore.\n\nTo proceed, please share:\n1. Full claims history (last 5 years)\n2. Current policy schedule\n3. List of procedures performed annually\n\nWe can typically get terms within 5 working days once we have the submission complete.\n\nBest regards,\nSophia Ng\nTrade Risk Solutions", sent_at: '2026-05-24T10:00:00Z', to: ['wei.chen@singhealth.com.sg'], cc: [] },
      { id: 'msg-003c', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Professional Indemnity Renewal – SingHealth', body_text: "Dear Dr. Chen,\n\nI am pleased to confirm that QBE has agreed to offer the 45-clinician PI policy at a competitive rate despite the prior claim.\n\nProposed terms:\n- Insurer: QBE Insurance (Singapore)\n- Limit: SGD 3M any one claim / SGD 6M aggregate\n- Premium: SGD 54,600 p.a.\n- Retroactive date: To be agreed\n\nThe formal quote letter is attached. Please review and let me know if you have any questions.\n\nBest regards,\nSophia Ng", sent_at: '2026-05-26T14:20:00Z', to: ['wei.chen@singhealth.com.sg'], cc: ['admin@singhealth.com.sg'] },
    ],
  },
  'thread-004': {
    thread: { id: 'thread-004', subject: 'Marine Cargo – Open Cover Proposal', contact_id: 'c-009', last_message_at: '2026-05-26T10:00:00Z', status: 'active', message_count: 2 },
    messages: [
      { id: 'msg-004a', direction: 'inbound', from_address: 'amanda.koh@swiftfreight.sg', subject: 'Marine Open Cover Enquiry', body_text: "Hi Trade Risk Solutions,\n\nSwift Freight operates 4 vessels. Our current marine liability insurer is exiting the Singapore market. We are urgently looking to place our marine cargo open cover with a new insurer.\n\nAnnual cargo value: approximately SGD 45M\nMain routes: Singapore–Batam, Singapore–Port Klang, Singapore–Jakarta\nCargo types: general merchandise, electronics, F&B\n\nPlease advise on coverage options.\n\nAmanda Koh\nFinance Manager", sent_at: '2026-05-21T06:30:00Z', to: ['hello@trade-risksol.com'], cc: [] },
      { id: 'msg-004b', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Marine Cargo – Open Cover Proposal', body_text: "Hi Amanda,\n\nThank you for your enquiry. We have obtained terms from Tokio Marine for a marine cargo open cover policy tailored to Swift Freight's routes.\n\nProposed Terms:\n- Insurer: Tokio Marine Insurance Singapore\n- Coverage: Institute Cargo Clauses (A) — All Risks\n- Policy basis: Open cover, declaratory\n- Annual estimated premium: SGD 28,400\n  (based on 0.063% rate on SGD 45M declared value)\n- 72-hour discovery clause\n- Sub-limits: Electronics SGD 5M per shipment\n\nThe policy can be bound within 3 business days. Shall we proceed to the next step?\n\nBest regards,\nMichael Wong\nTrade Risk Solutions", sent_at: '2026-05-26T10:00:00Z', to: ['amanda.koh@swiftfreight.sg'], cc: [] },
    ],
  },
  'thread-005': {
    thread: { id: 'thread-005', subject: 'D&O & Crime Insurance – Pinnacle Financial Services', contact_id: 'c-005', last_message_at: '2026-05-25T16:45:00Z', status: 'active', message_count: 4 },
    messages: [
      { id: 'msg-005a', direction: 'inbound', from_address: 'michelle.wong@pinnfin.com.sg', subject: 'D&O and Crime Insurance', body_text: "Hi,\n\nPinnacle Financial Services is a licensed fund manager regulated by MAS. We need to review our D&O liability and crime insurance before our next MAS inspection.\n\nCurrent D&O limit: SGD 5M (feels inadequate)\nFunds AUM: SGD 280M\nBoard: 6 directors\n\nWe also need a fidelity/crime policy. Can you help?\n\nMichelle Wong\nCompliance Director", sent_at: '2026-05-23T11:15:00Z', to: ['hello@trade-risksol.com'], cc: [] },
      { id: 'msg-005b', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Re: D&O and Crime Insurance', body_text: "Dear Michelle,\n\nThank you for reaching out. D&O and crime for MAS-regulated fund managers is an area we specialise in.\n\nGiven your AUM and MAS licensing, we would recommend:\n- D&O limit: SGD 20M (Side A, B, C)\n- Crime: SGD 5M (employee dishonesty + computer fraud)\n\nI will approach Chubb, AIG and Liberty for competitive terms. Can you share your current policy wording and any claims history?\n\nBest regards,\nSophia Ng", sent_at: '2026-05-23T14:00:00Z', to: ['michelle.wong@pinnfin.com.sg'], cc: [] },
      { id: 'msg-005c', direction: 'inbound', from_address: 'michelle.wong@pinnfin.com.sg', subject: 'Re: D&O and Crime Insurance', body_text: "Hi Sophia,\n\nAttached is our current policy schedule and 5-year claims history (nil claims). Please proceed with the market submission.\n\nWe need this in place before 15 June.\n\nMichelle", sent_at: '2026-05-24T09:00:00Z', to: ['operations@trade-risksol.com'], cc: ['cfo@pinnfin.com.sg'] },
      { id: 'msg-005d', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'D&O & Crime Insurance – Pinnacle Financial Services', body_text: "Dear Michelle,\n\nCongratulations — your D&O and crime policy has been bound effective 1 June.\n\n- D&O: Chubb, SGD 20M limit, premium SGD 38,500 p.a.\n- Crime: Chubb, SGD 5M limit, premium SGD 12,200 p.a.\n- Combined saving vs. market average: ~22%\n\nCertificates of insurance are attached for your records. We'll send the formal policy documents within 10 business days.\n\nThank you for choosing Trade Risk Solutions.\n\nBest regards,\nSophia Ng", sent_at: '2026-05-25T16:45:00Z', to: ['michelle.wong@pinnfin.com.sg'], cc: ['cfo@pinnfin.com.sg'] },
    ],
  },
  'thread-006': {
    thread: { id: 'thread-006', subject: 'Work Injury Compensation – Ng Precision Engineering', contact_id: 'c-016', last_message_at: '2026-05-25T11:30:00Z', status: 'active', message_count: 2 },
    messages: [
      { id: 'msg-006a', direction: 'inbound', from_address: 'ethan.ng@ngprecision.sg', subject: 'WIC Insurance — Looking for Alternative Insurer', body_text: "Hi,\n\nWe employ 85 workers at our precision engineering facility in Jurong. Our current WIC insurer (NTUC Income) has increased our premium by 40% this year despite a clean claims record.\n\nWe need a quote for WIC that is more competitive. Our payroll is SGD 3.8M.\n\nEthan Ng\nCFO, Ng Precision Engineering", sent_at: '2026-05-18T11:30:00Z', to: ['hello@trade-risksol.com'], cc: [] },
      { id: 'msg-006b', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Work Injury Compensation – Ng Precision Engineering', body_text: "Hi Ethan,\n\nI've obtained quotes from 4 insurers for your WIC policy renewal:\n\n| Insurer | Annual Premium | vs. Current |\n|---------|---------------|-------------|\n| AIG | SGD 22,800 | -20% |\n| Liberty | SGD 24,100 | -15% |\n| Tokio Marine | SGD 25,600 | -10% |\n| QBE | SGD 27,900 | -2% |\n\nAll policies comply with the Work Injury Compensation Act (WICA 2019). I recommend AIG — they have strong claims service in the manufacturing sector.\n\nShall I proceed to bind with AIG?\n\nBest regards,\nMichael Wong", sent_at: '2026-05-25T11:30:00Z', to: ['ethan.ng@ngprecision.sg'], cc: [] },
    ],
  },
  'thread-007': {
    thread: { id: 'thread-007', subject: 'Hull & Machinery Insurance – Coastal Marine Services', contact_id: 'c-012', last_message_at: '2026-05-24T13:00:00Z', status: 'active', message_count: 2 },
    messages: [
      { id: 'msg-007a', direction: 'inbound', from_address: 'henry.tan@coastalmarine.sg', subject: 'Hull & Machinery — Broker Change', body_text: "Hi,\n\nCoastal Marine Services operates 6 offshore support vessels (OSVs). We are looking to move our H&M coverage to a local broker who understands the Singapore market better.\n\nVessel values total approximately USD 28M. We do operations in the Straits, Batam, and occasionally Bay of Bengal.\n\nWould appreciate a market review.\n\nHenry Tan\nOperations Director", sent_at: '2026-05-20T12:30:00Z', to: ['hello@trade-risksol.com'], cc: [] },
      { id: 'msg-007b', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Hull & Machinery Insurance – Coastal Marine Services', body_text: "Hi Henry,\n\nThank you for considering TRS for your H&M placement. We have strong relationships with Lloyd's syndicates and local P&I clubs.\n\nFor your 6 OSVs at USD 28M total value, we have shortlisted:\n1. Lloyd's Syndicate 1414 (Ascot) — specialist OSV underwriter\n2. Tokio Marine — strong claims servicing in Singapore\n\nBoth can accommodate your trading limits including Bay of Bengal.\n\nCould we arrange a 30-minute call this week to review the vessel schedules before we submit to market?\n\nBest regards,\nSophia Ng\nTrade Risk Solutions", sent_at: '2026-05-24T13:00:00Z', to: ['henry.tan@coastalmarine.sg'], cc: [] },
    ],
  },
  'thread-008': {
    thread: { id: 'thread-008', subject: 'Marine Portfolio Consolidation – Lim Brothers Shipping', contact_id: 'c-017', last_message_at: '2026-05-24T09:20:00Z', status: 'active', message_count: 3 },
    messages: [
      { id: 'msg-008a', direction: 'inbound', from_address: 'vivian.lim@limshipping.sg', subject: 'Marine Portfolio Review', body_text: "Hi Trade Risk Solutions,\n\nLim Brothers Shipping currently has our marine portfolio split across 3 insurers. We believe we are overpaying and want to consolidate.\n\nCurrent setup:\n- Cargo (open cover): Liberty — SGD 68,000\n- Hull: AIG — USD 42,000 equiv.\n- P&I: UK Club via London broker\n\nTotal spend: ~SGD 172,000 p.a.\n\nPlease advise.\n\nVivian Lim\nFinance Director", sent_at: '2026-05-17T13:15:00Z', to: ['hello@trade-risksol.com'], cc: [] },
      { id: 'msg-008b', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Re: Marine Portfolio Review', body_text: "Dear Vivian,\n\nThank you for sharing the details. Consolidation often yields 15–25% savings plus the operational benefit of a single broker relationship.\n\nI will conduct a full market review and come back with a consolidated proposal. Do you prefer to retain UK Club for P&I or are you open to alternatives?\n\nBest regards,\nMichael Wong", sent_at: '2026-05-18T10:00:00Z', to: ['vivian.lim@limshipping.sg'], cc: [] },
      { id: 'msg-008c', direction: 'outbound', from_address: 'operations@trade-risksol.com', subject: 'Marine Portfolio Consolidation – Lim Brothers Shipping', body_text: "Dear Vivian,\n\nThe consolidated marine portfolio is now fully bound.\n\nSummary:\n- Cargo open cover: Tokio Marine — SGD 54,000 (-21% vs. Liberty)\n- Hull & Machinery: Lloyd's Syndicate 1414 — SGD 58,000 (-18% vs. AIG equivalent)\n- P&I: Shipowners Club (moved from UK Club, better Singapore coverage) — SGD 30,000\n\nTotal: SGD 142,000 p.a. — saving of SGD 30,000 (18%)\n\nAll documents are attached. Welcome to TRS!\n\nBest regards,\nMichael Wong", sent_at: '2026-05-24T09:20:00Z', to: ['vivian.lim@limshipping.sg'], cc: ['ops@limshipping.sg'] },
    ],
  },
}

export const MOCK_THREAD_SUMMARIES: Record<string, Array<{ id: string; summary: string; next_action: string; draft_reply: string; created_at: string }>> = {
  'thread-001': [
    {
      id: 'sum-001',
      summary: 'James Lim from Meridian Logistics is seeking trade credit insurance for SGD 12M annual revenue with exposure to 10 buyers in Indonesia, Malaysia and Vietnam. He provided buyer breakdown — PT Nusantara is the largest at SGD 3.2M. One prior bad debt of SGD 180K. Looking to start by 1 July.',
      next_action: 'Call James to discuss Option 1 (Euler Hermes) vs Option 2 (Coface). Recommend Option 1 given Indonesian buyer exposure.',
      draft_reply: "Hi James,\n\nI wanted to follow up on the two options I sent through. Given your concentration in Indonesia (PT Nusantara at SGD 3.2M), I would lean towards Option 1 with Euler Hermes — they have a dedicated Singapore team and strong on-the-ground claims experience in Jakarta.\n\nAre you available for a 20-minute call this week to run through the policy terms before we proceed?\n\nBest regards,\nSophia Ng\nTrade Risk Solutions",
      created_at: '2026-05-27T10:00:00Z',
    }
  ],
  'thread-002': [
    {
      id: 'sum-002',
      summary: 'Sarah Tan from Vertex Tech is seeking a bundled cyber liability (SGD 10M), business interruption, and PI package. She processes payments for 50+ enterprise clients and recently had a security audit flagging gaps. A proposal featuring AIG Cyber Edge at SGD 68,000 was sent. Awaiting response.',
      next_action: 'Follow up by Friday if no response. Offer to walk through the cyber policy exclusions on a call.',
      draft_reply: "Hi Sarah,\n\nJust checking in to see if you had a chance to review the AIG Cyber Edge proposal. I'm happy to schedule a 30-minute call to walk through the coverage terms — particularly the exclusions around payment card industry (PCI) compliance incidents, which are relevant to your business.\n\nI'm available Thursday 2–5pm or Friday morning this week.\n\nBest regards,\nMichael Wong",
      created_at: '2026-05-27T08:00:00Z',
    }
  ],
  'thread-003': [
    {
      id: 'sum-003',
      summary: 'SingHealth Group urgently needs PI renewal for 45 clinicians by 30 June after their previous insurer declined due to a SGD 320K claim (cardiac complication). QBE has agreed to offer terms at SGD 54,600 for SGD 3M/6M limits. Formal quote has been sent.',
      next_action: 'Chase Dr. Chen for policy acceptance. If no response by 29 May, escalate to his admin contact.',
      draft_reply: "Dear Dr. Chen,\n\nI hope you have had a chance to review the QBE proposal. Given your renewal date of 30 June, I would recommend we aim to bind by 10 June to allow time for documentation.\n\nPlease let me know if you have any questions about the retroactive date or the claims notification requirements — these are the two areas worth discussing given your claims history.\n\nBest regards,\nSophia Ng",
      created_at: '2026-05-26T15:00:00Z',
    }
  ],
}

export const MOCK_OUTBOUND_LEADS = [
  { id: 'ob-001', record_type: 'person', source: 'people_search', linkedin_url: 'https://linkedin.com/in/alice-chan-sg', full_name: 'Alice Chan', headline: 'CFO at Raffles Medical Group', current_title: 'Chief Financial Officer', current_company: 'Raffles Medical Group', location: 'Singapore', email: 'alice.chan@rafflesmedical.com', email_status: 'verified', status: 'contacted', notes: 'Reached out re group hospitalisation renewal. She mentioned current policy expiring in Aug.', created_at: '2026-05-20T06:00:00Z' },
  { id: 'ob-002', record_type: 'person', source: 'url_lookup', linkedin_url: 'https://linkedin.com/in/ben-lim-ceo', full_name: 'Ben Lim', headline: 'Founder & CEO at LogiNow Pte Ltd', current_title: 'Founder & CEO', current_company: 'LogiNow Pte Ltd', location: 'Singapore', email: 'ben@loginow.sg', email_status: 'verified', status: 'new', notes: null, created_at: '2026-05-21T07:00:00Z' },
  { id: 'ob-003', record_type: 'person', source: 'people_search', linkedin_url: 'https://linkedin.com/in/cynthia-koh-ops', full_name: 'Cynthia Koh', headline: 'Operations Director, Pacific Industrial', current_title: 'Operations Director', current_company: 'Pacific Industrial Pte Ltd', location: 'Singapore', email: 'cynthia.koh@pacificindustrial.sg', email_status: 'verified', status: 'qualified', notes: 'Interested in CAR + 3rd party liability for 3 upcoming projects. Sent proposal draft.', created_at: '2026-05-19T08:00:00Z' },
  { id: 'ob-004', record_type: 'person', source: 'company_search', linkedin_url: 'https://linkedin.com/in/derek-wu-finance', full_name: 'Derek Wu', headline: 'VP Finance, SunAsia Energy', current_title: 'VP Finance', current_company: 'SunAsia Energy', location: 'Singapore', email: 'derek.wu@sunasia-energy.sg', email_status: 'guessed', status: 'new', notes: null, created_at: '2026-05-22T09:00:00Z' },
  { id: 'ob-005', record_type: 'person', source: 'people_search', linkedin_url: 'https://linkedin.com/in/elaine-ng-legal', full_name: 'Elaine Ng', headline: 'Managing Partner, Ng & Tan LLP', current_title: 'Managing Partner', current_company: 'Ng & Tan LLP', location: 'Singapore', email: 'elaine@ngtanlaw.sg', email_status: 'verified', status: 'contacted', notes: 'Law firm PI enquiry. Sent Q&A on retroactive date requirements for Singapore firms.', created_at: '2026-05-18T10:00:00Z' },
  { id: 'ob-006', record_type: 'person', source: 'people_search', linkedin_url: 'https://linkedin.com/in/frank-toh-coo', full_name: 'Frank Toh', headline: 'COO at BioPharma Asia', current_title: 'COO', current_company: 'BioPharma Asia Pte Ltd', location: 'Singapore', email: 'frank.toh@biopharmaasia.sg', email_status: 'verified', status: 'disqualified', notes: 'Not interested — already have a broker. Mark for re-engagement in 12 months.', created_at: '2026-05-15T11:00:00Z' },
  { id: 'ob-007', record_type: 'person', source: 'url_lookup', linkedin_url: 'https://linkedin.com/in/grace-lim-hrd', full_name: 'Grace Lim', headline: 'HR Director at Changi Airport Group', current_title: 'HR Director', current_company: 'Changi Airport Group', location: 'Singapore', email: 'grace.lim@changiairport.com', email_status: 'verified', status: 'new', notes: null, created_at: '2026-05-23T12:00:00Z' },
  { id: 'ob-008', record_type: 'person', source: 'people_search', linkedin_url: 'https://linkedin.com/in/harry-tan-cfo', full_name: 'Harry Tan', headline: 'CFO at Temasek-linked F&B Group', current_title: 'CFO', current_company: 'Koufu Group Limited', location: 'Singapore', email: 'harry.tan@koufu.com.sg', email_status: 'verified', status: 'contacted', notes: 'Reached out re employee benefits renewal. 2,400 staff across 50 outlets. Following up.', created_at: '2026-05-17T13:00:00Z' },
  { id: 'ob-009', record_type: 'person', source: 'company_search', linkedin_url: 'https://linkedin.com/in/irene-ong-tech', full_name: 'Irene Ong', headline: 'CTO at FinTech Innovations', current_title: 'CTO', current_company: 'FinTech Innovations Pte Ltd', location: 'Singapore', email: 'irene.ong@fintechinno.sg', email_status: 'guessed', status: 'new', notes: null, created_at: '2026-05-24T14:00:00Z' },
  { id: 'ob-010', record_type: 'person', source: 'people_search', linkedin_url: 'https://linkedin.com/in/jason-chen-logistics', full_name: 'Jason Chen', headline: 'Supply Chain Director, DHL Singapore', current_title: 'Supply Chain Director', current_company: 'DHL Supply Chain Singapore', location: 'Singapore', email: 'jason.chen@dhl.com', email_status: 'verified', status: 'qualified', notes: 'Interested in marine cargo open cover and trade credit combo. Proposal pending approval from HQ.', created_at: '2026-05-16T09:00:00Z' },
  { id: 'ob-011', record_type: 'company', source: 'company_search', linkedin_url: 'https://linkedin.com/company/keppel-logistics', full_name: 'Keppel Logistics', headline: 'Integrated logistics provider', current_title: null, current_company: 'Keppel Logistics', location: 'Singapore', email: null, email_status: null, status: 'new', notes: null, created_at: '2026-05-25T15:00:00Z' },
  { id: 'ob-012', record_type: 'person', source: 'people_search', linkedin_url: 'https://linkedin.com/in/linda-soh-risk', full_name: 'Linda Soh', headline: 'Risk Manager at Singapore Exchange', current_title: 'Risk Manager', current_company: 'Singapore Exchange Limited (SGX)', location: 'Singapore', email: 'linda.soh@sgx.com', email_status: 'verified', status: 'new', notes: null, created_at: '2026-05-26T10:00:00Z' },
]

export const MOCK_OUTBOUND_HISTORY = [
  { id: 'search-001', sector: 'Logistics & Supply Chain', location: 'Singapore', product_type: 'Marine Cargo', roles_targeted: ['CFO', 'Finance Director', 'Operations Director'], status: 'completed', company_count: 12, created_at: '2026-05-26T23:00:00Z' },
  { id: 'search-002', sector: 'Healthcare & Medical', location: 'Singapore', product_type: 'Professional Indemnity', roles_targeted: ['CEO', 'COO', 'Administration Director'], status: 'completed', company_count: 8, created_at: '2026-05-25T23:00:00Z' },
  { id: 'search-003', sector: 'Construction & Engineering', location: 'Singapore', product_type: 'Contractor All Risk', roles_targeted: ['Procurement Manager', 'Project Director', 'CFO'], status: 'completed', company_count: 15, created_at: '2026-05-24T23:00:00Z' },
  { id: 'search-004', sector: 'Financial Services', location: 'Singapore', product_type: 'D&O Liability', roles_targeted: ['CEO', 'CFO', 'Compliance Director'], status: 'completed', company_count: 10, created_at: '2026-05-23T23:00:00Z' },
  { id: 'search-005', sector: 'Manufacturing', location: 'Singapore', product_type: 'Work Injury Compensation', roles_targeted: ['HR Director', 'CFO', 'COO'], status: 'completed', company_count: 18, created_at: '2026-05-22T23:00:00Z' },
]

export const MOCK_OUTBOUND_SCHEDULES = [
  { id: 'sched-001', query: 'Logistics companies Singapore marine cargo', roles: ['CFO', 'Finance Director', 'Operations Director'], max_companies: 10, frequency: 'daily', is_active: true, next_run_at: '2026-05-28T23:00:00Z', last_run_at: '2026-05-27T23:00:00Z', runs_count: 12, created_at: '2026-05-16T00:00:00Z' },
  { id: 'sched-002', query: 'Healthcare clinics professional indemnity Singapore', roles: ['CEO', 'COO', 'Medical Director'], max_companies: 8, frequency: 'weekly', is_active: true, next_run_at: '2026-06-02T23:00:00Z', last_run_at: '2026-05-26T23:00:00Z', runs_count: 4, created_at: '2026-05-01T00:00:00Z' },
  { id: 'sched-003', query: 'Construction engineering Contractor All Risk Singapore', roles: ['Procurement Manager', 'Project Director', 'CFO'], max_companies: 12, frequency: 'weekly', is_active: false, next_run_at: null, last_run_at: '2026-05-20T23:00:00Z', runs_count: 6, created_at: '2026-04-22T00:00:00Z' },
]

function geminiUsageRow(id: string, date: string, feature: string, input: number, output: number) {
  const cost = (input * 0.000001875 + output * 0.0000075)
  return { id, created_at: date, feature, input_tokens: input, output_tokens: output, cost_usd: parseFloat(cost.toFixed(6)) }
}

export const MOCK_AI_USAGE = [
  geminiUsageRow('gu-001', '2026-05-01T08:12:00Z', 'auto_summarize', 1850, 320),
  geminiUsageRow('gu-002', '2026-05-01T09:30:00Z', 'email_analysis', 980, 280),
  geminiUsageRow('gu-003', '2026-05-02T07:45:00Z', 'engagement_draft', 2100, 450),
  geminiUsageRow('gu-004', '2026-05-02T10:15:00Z', 'auto_summarize', 1620, 310),
  geminiUsageRow('gu-005', '2026-05-03T08:00:00Z', 'rag_draft', 3200, 580),
  geminiUsageRow('gu-006', '2026-05-03T11:00:00Z', 'email_analysis', 1100, 260),
  geminiUsageRow('gu-007', '2026-05-04T09:20:00Z', 'engagement_draft', 1900, 420),
  geminiUsageRow('gu-008', '2026-05-05T07:30:00Z', 'auto_summarize', 2400, 380),
  geminiUsageRow('gu-009', '2026-05-06T10:00:00Z', 'rag_draft', 3500, 620),
  geminiUsageRow('gu-010', '2026-05-07T08:45:00Z', 'email_analysis', 1250, 290),
  geminiUsageRow('gu-011', '2026-05-08T09:00:00Z', 'engagement_draft', 2050, 440),
  geminiUsageRow('gu-012', '2026-05-09T07:15:00Z', 'auto_summarize', 1780, 330),
  geminiUsageRow('gu-013', '2026-05-10T10:30:00Z', 'rag_draft', 2900, 550),
  geminiUsageRow('gu-014', '2026-05-11T08:00:00Z', 'email_analysis', 1050, 270),
  geminiUsageRow('gu-015', '2026-05-12T09:45:00Z', 'engagement_draft', 2200, 460),
  geminiUsageRow('gu-016', '2026-05-13T07:30:00Z', 'auto_summarize', 1950, 350),
  geminiUsageRow('gu-017', '2026-05-14T10:00:00Z', 'rag_draft', 3100, 590),
  geminiUsageRow('gu-018', '2026-05-15T08:30:00Z', 'email_analysis', 1180, 285),
  geminiUsageRow('gu-019', '2026-05-16T09:15:00Z', 'engagement_draft', 1850, 415),
  geminiUsageRow('gu-020', '2026-05-17T07:45:00Z', 'auto_summarize', 2100, 360),
  geminiUsageRow('gu-021', '2026-05-18T10:30:00Z', 'rag_draft', 2800, 530),
  geminiUsageRow('gu-022', '2026-05-19T08:00:00Z', 'email_analysis', 1300, 295),
  geminiUsageRow('gu-023', '2026-05-20T09:30:00Z', 'engagement_draft', 2300, 480),
  geminiUsageRow('gu-024', '2026-05-21T07:15:00Z', 'auto_summarize', 1700, 325),
  geminiUsageRow('gu-025', '2026-05-22T10:00:00Z', 'rag_draft', 3400, 610),
  geminiUsageRow('gu-026', '2026-05-23T08:45:00Z', 'email_analysis', 1150, 275),
  geminiUsageRow('gu-027', '2026-05-24T09:00:00Z', 'engagement_draft', 2000, 435),
  geminiUsageRow('gu-028', '2026-05-25T07:30:00Z', 'auto_summarize', 2250, 370),
  geminiUsageRow('gu-029', '2026-05-26T10:15:00Z', 'rag_draft', 3050, 565),
  geminiUsageRow('gu-030', '2026-05-27T08:00:00Z', 'email_analysis', 1200, 288),
]

export const MOCK_AUDIT_LOG = [
  { id: 'al-001', user_email: 'sophia.ng@trade-risksol.com', action: 'lead_status_updated', resource_type: 'inbound_lead', resource_id: 'lead-001', metadata: { from: 'contacted', to: 'qualified' }, created_at: '2026-05-27T09:45:00Z' },
  { id: 'al-002', user_email: 'michael.wong@trade-risksol.com', action: 'email_sent', resource_type: 'email_thread', resource_id: 'thread-002', metadata: { subject: 'Cyber Liability Policy – Vertex Tech Solutions' }, created_at: '2026-05-27T07:15:00Z' },
  { id: 'al-003', user_email: 'sophia.ng@trade-risksol.com', action: 'draft_generated', resource_type: 'email_thread', resource_id: 'thread-001', metadata: { feature: 'engagement_draft' }, created_at: '2026-05-27T09:30:00Z' },
  { id: 'al-004', user_email: 'sophia.ng@trade-risksol.com', action: 'email_sent', resource_type: 'email_thread', resource_id: 'thread-003', metadata: { subject: 'Professional Indemnity Renewal – SingHealth' }, created_at: '2026-05-26T14:20:00Z' },
  { id: 'al-005', user_email: 'michael.wong@trade-risksol.com', action: 'outbound_lead_status_updated', resource_type: 'outbound_lead', resource_id: 'ob-003', metadata: { from: 'contacted', to: 'qualified' }, created_at: '2026-05-26T11:00:00Z' },
  { id: 'al-006', user_email: 'sophia.ng@trade-risksol.com', action: 'lead_status_updated', resource_type: 'inbound_lead', resource_id: 'lead-005', metadata: { from: 'proposal', to: 'converted' }, created_at: '2026-05-25T16:50:00Z' },
  { id: 'al-007', user_email: 'michael.wong@trade-risksol.com', action: 'email_sent', resource_type: 'email_thread', resource_id: 'thread-006', metadata: { subject: 'Work Injury Compensation – Ng Precision Engineering' }, created_at: '2026-05-25T11:30:00Z' },
  { id: 'al-008', user_email: 'sophia.ng@trade-risksol.com', action: 'draft_generated', resource_type: 'email_thread', resource_id: 'thread-003', metadata: { feature: 'rag_draft' }, created_at: '2026-05-26T13:00:00Z' },
  { id: 'al-009', user_email: 'michael.wong@trade-risksol.com', action: 'outbound_search_run', resource_type: 'ob_search_log', resource_id: 'search-001', metadata: { sector: 'Logistics', company_count: 12 }, created_at: '2026-05-26T23:00:00Z' },
  { id: 'al-010', user_email: 'sophia.ng@trade-risksol.com', action: 'lead_status_updated', resource_type: 'inbound_lead', resource_id: 'lead-017', metadata: { from: 'proposal', to: 'converted' }, created_at: '2026-05-24T09:30:00Z' },
]

export const MOCK_CC_PARTICIPANTS = [
  { id: 'cc-finance@meridianlog.com.sg', email: 'finance@meridianlog.com.sg', first_name: 'Finance', last_name: 'Team', company: 'Meridian Logistics', status: 'cc', source: 'email', isCC: true, created_at: '2026-05-26T01:30:00Z' },
  { id: 'cc-cfo@pinnfin.com.sg', email: 'cfo@pinnfin.com.sg', first_name: 'CFO', last_name: 'Office', company: 'Pinnacle Financial Services', status: 'cc', source: 'email', isCC: true, created_at: '2026-05-24T09:00:00Z' },
  { id: 'cc-admin@singhealth.com.sg', email: 'admin@singhealth.com.sg', first_name: 'Admin', last_name: 'SingHealth', company: 'SingHealth Group', status: 'cc', source: 'email', isCC: true, created_at: '2026-05-26T14:20:00Z' },
  { id: 'cc-it@vertextech.sg', email: 'it@vertextech.sg', first_name: 'IT', last_name: 'Department', company: 'Vertex Tech Solutions', status: 'cc', source: 'email', isCC: true, created_at: '2026-05-27T07:15:00Z' },
  { id: 'cc-ops@limshipping.sg', email: 'ops@limshipping.sg', first_name: 'Operations', last_name: 'Team', company: 'Lim Brothers Shipping', status: 'cc', source: 'email', isCC: true, created_at: '2026-05-24T09:20:00Z' },
]

export const MOCK_INBOUND_DRAFT = (name: string, topic: string) =>
  `Hi ${name.split(' ')[0]},\n\nThank you for reaching out to Trade Risk Solutions. We've received your enquiry about ${topic || 'insurance coverage'} and a specialist from our team will follow up within 1 business day.\n\nIn the meantime, if you have any urgent questions, feel free to reply to this email or call us at +65 6227 8988.\n\nBest regards,\nTrade Risk Solutions`

export const MOCK_ENGAGEMENT_DRAFT = (_threadId: string) =>
  `Thank you for your message. I've reviewed the details you've shared and I'm preparing a tailored proposal for your consideration.\n\nI'll have this ready for you by end of week. Please don't hesitate to reach out if you have any questions in the meantime.\n\nBest regards,\nTrade Risk Solutions`

export const MOCK_RAG_INDEX = [
  { id: 'rag-001', file_name: 'TRS_Product_Guide_2026.pdf', file_type: 'pdf', chunks: 142, last_indexed: '2026-05-27T18:00:00Z', status: 'indexed' },
  { id: 'rag-002', file_name: 'Marine_Cargo_Clauses_ICC_A.pdf', file_type: 'pdf', chunks: 58, last_indexed: '2026-05-27T18:01:00Z', status: 'indexed' },
  { id: 'rag-003', file_name: 'Trade_Credit_Underwriting_Guide.pdf', file_type: 'pdf', chunks: 87, last_indexed: '2026-05-27T18:02:00Z', status: 'indexed' },
  { id: 'rag-004', file_name: 'Singapore_WIC_Act_2019.pdf', file_type: 'pdf', chunks: 203, last_indexed: '2026-05-27T18:03:00Z', status: 'indexed' },
  { id: 'rag-005', file_name: 'Professional_Indemnity_FAQ.pdf', file_type: 'pdf', chunks: 64, last_indexed: '2026-05-27T18:04:00Z', status: 'indexed' },
]
